### PR TITLE
B2 83 remove cms file

### PR DESCRIPTION
**Pull request by nelsW70**
PR:
Closes [B2-83](https://b2io.atlassian.net/browse/B2-83)

- deleted cms file and references to it in page index files
- deleted page slug files
- created culture and contact folders and index files

### CODE REVIEW

**Review by asingleton6 — APPROVED** [review]
Looks good to me!

**Review by tborres — APPROVED** [review]
Everything seems to be working. I'm interested to hear from @mewdriller if we should keep the `slug` files for work and blog, but we could always revive them when we need them.

🚢

**Comment by nelsW70** [comment]
> Everything seems to be working. I'm interested to hear from @mewdriller if we should keep the `slug` files for work and blog, but we could always revive them when we need them.
> 
> 🚢

@tborres, should I add them back in without imports or just merge?

**Comment by tborres** [comment]
Merge it!

**Pull request merged**
