### PR TITLE
chore: Upgrade gatsby

### LINKED ISSUE #340: Upgrade to Gatsby v2
> "We should upgrade to Gatsby v2 now that it’s released. There are a lot of improvements there that will help us."
> \- Mew Driller

### PR DESCRIPTION
**Pull request by tborres**
Closes #340 

Upgrade Gatsby

### CODE REVIEW

**Comment by tborres** [comment]
There appears to be an issue with the right most orbits on the small screen:

image

**Comment by reeddunkle** [comment]
I tested on Windows: Chrome, Firefox, Edge, IE11, and on Android Chrome. The links all seem to work, the content all seems there. Seems good.

Things that I'm not sure are related to this PR:

### General

* The elements on the homepage jump around as I scroll (desktop and mobile)

### IE11

* The blog subtitle on IE11 isn't reacting to the screen size the way it's meant to:

b2io-blog-header-IE11

* If I click from the nav bar link `Clients` to `Contact`, the contact form isn't positioned correctly. This doesn't seem to occur if I load the link fresh, and then click on `Contact`.

b2io-contact-IE11

### Edge

* Same as above with `Contact`, but the positioning is different on Edge

b2io-contact-Edge

**Comment by tborres** [comment]
Thanks, Reed!

1. _The elements on the homepage jump around as I scroll (desktop and mobile)_ - I'm not positive on the jumping issue, but if it's related to the images loading in then that's a pre-existing issue. Does it occur for you on the existing site?
2. _The blog subtitle on IE11 isn't reacting to the screen size the way it's meant to_ - This is a pre-existing known [issue](https://github.com/b2io/base2.io/issues/374)
3. _If I click from the nav bar link `Clients` to `Contact`, the contact form isn't positioned correctly. This doesn't seem to occur if I load the link fresh, and then click on `Contact`._ - This seems to be new.

**Comment by chawkins-nj** [comment]
I think _the elements on the homepage jump around as I scroll_ is just the same issue with how images are loading. The test I used was, is there anything (like that) happening in this deployment preview that isn't happening in production as well... and I couldn't find any.

**Pull request merged**
