### PR TITLE
doc(shortcut): insert/delete spreadsheet columns

### PR DESCRIPTION
**Pull request by tborres**
post-6-09

### CODE REVIEW

**Comment by mewdriller** [comment]
I'm not sure if this will work well on the markdown processor / styles on our site, but in GitHub and StackOverflow if you want a pretty keyboard shortcut you can use `<kbd>ALT</kbd>+<kbd>i</kbd>+<kbd>c</kbd>`, etc.

e.g.: <kbd>ALT</kbd>+<kbd>i</kbd>+<kbd>c</kbd>

**Comment by mewdriller** [comment]
Looks good. :+1:

**Comment by tborres** [comment]
`<kbd>` doesn't look very good on our site. It just looks like courier new. Good to know though.

**Comment by mewdriller** [comment]
If only for reference, it looks like on GitHub these are the styles getting applied to `<kbd>` elements:

```css
.markdown-body kbd {
  display: inline-block;
  padding: 3px 5px;
  font-size: 11px;
  line-height: 10px;
  color: #555;
  vertical-align: middle;
  background-color: #fcfcfc;
  border: solid 1px #ccc;
  border-bottom-color: #bbb;
  border-radius: 3px;
  box-shadow: inset 0 -1px 0 #bbb;
}

kbd {
  font: 11px Consolas, "Liberation Mono", Menlo, Courier, monospace;
}
```

**Comment by tborres** [comment]
Thanks. If I have time tomorrow I may update the post to use those styles.

On Tue, Jun 9, 2015 at 1:21 PM, Drew Miller <notifications@github.com>
wrote:

> If only for reference, it looks like on GitHub these are the styles
> getting applied to <kbd> elements:
>
> .markdown-body kbd {
>   display: inline-block;
>   padding: 3px 5px;
>   font-size: 11px;
>   line-height: 10px;
>   color: #555;
>   vertical-align: middle;
>   background-color: #fcfcfc;
>   border: solid 1px #ccc;
>   border-bottom-color: #bbb;
>   border-radius: 3px;
>   box-shadow: inset 0 -1px 0 #bbb;
> }
> kbd {
>   font: 11px Consolas, "Liberation Mono", Menlo, Courier, monospace;
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/b2io/base2.io/pull/31#issuecomment-110438821>.
>



-- 
Thanks,

Tony Borres
412.212.3017
*Base Two*

**Pull request merged**
