### PR TITLE
feat(contact-us): Contact Us design assets

### LINKED ISSUE #204: Purchase and implement design assets
Create a BaseTwo Shutterstock account (info@ and company card) to make sure the ownership of the license is with the company. Purchase the following images:

- [x] **Stock illustration ID: 57461610**
_America city lights. Maps from NASA imagery_
 To be Purchased from Shutterstock via individual image purchase or subscription (depending on what else we decide to use from there)  

- [x] **Stock illustration ID: 248399542**
_Moon Surface_
 To be Purchased from Shutterstock via individual image purchase or subscription (depending on what else we decide to use from there)

- [x] Resize and implement images into Contact Us section. 
- [x] Ensure everything looks good on all supported browsers.

### PR DESCRIPTION
**Pull request by csteinert**
Closes #204

### CODE REVIEW

**Comment by MLKendall** [comment]
The Earth is not properly aligned in IE
ie view

**Comment by MLKendall** [comment]
Contact Information is too close to the moon image in tablet view (this is using the Chrome Dev Tools Preview).  
tabletview

**Comment by MLKendall** [comment]
Can the Earth image be wider on mobile? And can the button be smaller, like in the design doc (sorry if I did not catch that when this section was first completed?

I also think the text on the "satellites and internet" phrase could be bigger.  It is a little small in the design doc as well.  I vote for making it larger now that I see it.  Thoughts?
mobileview

**Comment by MLKendall** [comment]
This is minor, especially since we aren't animating it, but there was a satellite orbiting the earth in the design doc.  It was the satellite svg like in the scroll indicator.  Can we include it?  If not, don't let it be a blocker to this going out.

**Comment by csteinert** [comment]
Re: the satellite, I'd like to add that later as an enhancement. I think it might be kinda tough.

**Comment by MLKendall** [comment]
Make Contact Button is now misaligned in IE:
makecontactshift

**Pull request merged**
